# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f5527d99854361ce4031e3c880c614c3b8769299cf9157b842b0b7cf57f1da50f9632dcd023d09906f8ecf9860348810bdbe4979c36a0657f9ed8e606b04c18

test:
  secret_key_base: 062faddc7f42862e84f5bcf3461c71aa8b93cdadf4127ae9a9fee4f796d24da198342c62b520c0716fcb88c621e2203715162fd4094c0102118394869106472e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
